# Generated by Django 2.2.5 on 2019-09-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190922_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp_codes',
            options={'ordering': ('date_created',)},
        ),
        migrations.AlterField(
            model_name='otp_codes',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
